### ISSUE TITLE
Does q2-aldex2 works with q2-picrust output?

### ISSUE THREAD

**Issue by bsmoda** [mortonjt/q2-aldex2#11]
Hi there @ggloor !

First, thanks for creating a q2-plugin for ALDEx2!
 I have tried to use your plugin with an output from q2-picrust plugin, which is very similar to an otu-table, but instead of a frequency counts, it has a score for each feature that is a float number. I think that was the problem because I've got this error:

```shell
Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_aldex2.R /tmp/tmp7g95b_0l/input.tsv.biom /tmp/tmp7g95b_0l/input.map.txt neoadjuvant_treatment_response 128 t all /tmp/tmp7g95b_0l/output.summary.txt

R version 3.5.1 (2018-07-02) 
[1] "aldex.clr: generating Monte-Carlo instances and clr values"
[1] "operating in serial mode"
Error in aldex.clr.function(as.data.frame(reads), conds, mc.samples, denom,  : 
  not all reads are integers
Calls: aldex -> aldex.clr -> aldex.clr -> aldex.clr.function
Execution halted
Traceback (most recent call last):
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_aldex2/_method.py", line 59, in aldex2
    run_commands([cmd])
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_aldex2/_method.py", line 21, in run_commands
    subprocess.run(cmd, check=True)
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_aldex2.R', '/tmp/tmp7g95b_0l/input.tsv.biom', '/tmp/tmp7g95b_0l/input.map.txt', 'neoadjuvant_treatment_response', '128', 't', 'all', '/tmp/tmp7g95b_0l/output.summary.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__
    results = action(**arguments)
  File "</mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/decorator.py:decorator-gen-485>", line 2, in aldex2
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/mnt/data2/lbcb/conda/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_aldex2/_method.py", line 63, in aldex2
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running ALDEx2 in R (return code 1), please inspect stdout and stderr to learn more.
```
The [Picrust2 tutorial](https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.1.4-beta)#picrust2-pipeline) recommends the use of ALDEx R package for the output analysis, but now I'm confused about this error, can clarify this for me, please?

**Comment by dgiguer** [comment]
Hi @bsmoda, 

The count table needs to be imported as an artifact before running the `q2-aldex` command (example of importing raw tsv in this [wiki](https://github.com/dgiguer/q2-aldex2/wiki). Your table from the picrust should be in this format (sample by column, features by row, first column name `featureid`: 

featureid|X1\_ANS|X1\_BNS|X1\_CNS|X1\_DNS|X2\_ANS|X2\_CNS|X2\_DNS|X1\_AS|X1\_BS|X1\_CS|X1\_DS|X2\_AS|X2\_CS|X2\_DS
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
A:D:A:D|347|271|396|317|391|260|620|8|1|1|2|0|1|3
A:D:A:E|436|361|461|241|410|387|788|83|6|8|12|0|3|2
A:E:A:D|476|288|378|215|412|430|591|997|3747|662|421|37|75|6353
A:E:A:E|513|307|424|381|499|447|709|10547|12033|5394|15998|293|1816|33

If your table is in this format, can you post an example of what your count table looks like, as well as the exact command you used? Thanks!

**Comment by bsmoda** [comment]
This is an example of my feature table:

| featureid 	| 180503650905-1-1-1 	| 180503650896-1-1-1 	| 180503650897-1-1-1 	|   	|
|--------	|--------------------	|--------------------	|--------------------	|---	|
| K00001 	| 0.0                	| 25.5               	| 11.5               	|   	|
| K00002 	| 0.0                	| 0.0                	| 0.0                	|   	|
| K00003 	| 15.0               	| 10879.73           	| 10045.08           	|   	|
| K00004 	| 0.0                	| 565.4              	| 1669.67            	|   	|
| K00005 	| 0.0                	| 1872.15 474.0      	|                    	|   	|
| K00007 	| 0.0                	| 0.0                	| 0.0                	|   	|
| K00008 	| 0.0                	| 35.0               	| 12.5               	|   	|
| K00009 	| 0.0                	| 411.75             	| 231.25             	|   	|
| K00010 	| 0.0                	| 1194.0             	| 188.0              	|   	|

I had converted to qiime2 artifact as mentioned in the wiki example and run this command:
``` shell
qiime aldex2 aldex2 \
  --i-table ko-case-wo_notapplicable.qza \
  --m-metadata-file metadata.tsv \
  --m-mtadata-column neoadjuvant_treatment_response \
  --output-dir aldex2\adj-treat-response
```
I've got the same error as I mentioned above, regarding that not all reads are integer. Your feature-table example has only integer numbers. But the output from q2-picrust2 generates this same table with float numbers.

**Comment by dgiguer** [comment]
aldex2 accepts only integers because the Dirichlet instances are a model of counting, not of probability (counts can only be integer numbers). the easiest work around would be to just round the numbers to integers. the picrust2 tutorial does mention rounding the numbers prior to using aldex2. we will modify the documentation to mention this!
